spring:
  application:
    name: greeting-microservice
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
greeting-microservice:
  greeting: "HI, my english int's very good!'"
  default-value: "U2'"
